name: geoflutterfire3
description: GeoFlutterFire3 is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.0
homepage: https://github.com/AbderraoufKhodja/geoflutterfire3
publish_to: https://pub.dev

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.0.4
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
